version: '3'
services:

  authentication:
    build:
      context: JWTauthentication
      dockerfile: Dockerfile
   
    restart: always
    ports:
      - "8098:8098"
    deploy:
      resources:
        limits:
          cpus: '0.001'
          memory: 3gb
  

  serving:
    build:
      context: serving2/serving2
      dockerfile: Dockerfile
   
    restart: always
    ports:
      - "8051:8051"
  

  random-recommandation:
    build:
      context: random-recommandation-service
      dockerfile: Dockerfile
   
    restart: always
    ports:
      - "8049:8049"