server:
  port: 8049
spring:
  data:
     mongodb:
        host:  ${MONGO_HOST}
        port:  ${MONGO_PORT}
        database: ${MONGO_COLLECTION}
        authentication-database: admin
  cloud:
    stream:
      kafka:
        binder:
          brokers:  http://${KAFKA_HOST}:${KAFKA_PORT}
      bindings:

        request-in:
          destination: requestRecommandation
          contentType: text/plain

        event-in:
          destination: adsToBeConsumed
          contentType: application/json

        recommandation_out:
          destination: recommandation
          contentType: application/json
#  zipkin:
#    base-url: http://192.168.99.100:9411/
  application:
      name: random-recommandation-service
logging:
   level: com.assignment.springboot.mongo=DEBUG

#spring.data.mongodb.username=root
#spring.data.mongodb.password=GH15935746
