spring:
  cloud:
    stream:
      kafka:
        binder:
#          brokers: 192.168.99.100:19092
           brokers:  http://${KAFKA_HOST}:${KAFKA_PORT}

      bindings:
        login-out:
          destination: login-logout
          contentType: application/json
        events-out:
          destination: userEvent
          contentType: application/json
#  zipkin:-
#    base-url: http://192.168.99.100:9411/
      base-url: http://{ZIPKIN_HOST}:${ZIPKIN_PORT}

  jpa:
     show-sql : true
     hibernate:
         ddl-auto : update

     properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect

  datasource :
     driver-class-name: com.mysql.jdbc.Driver
#     url : jdbc:mysql://192.168.99.100:3306/security?allowPublicKeyRetrieval=true&useSSL=false
     url: jdbc:mysql://${MYSQL_DB_HOST}:${MYSQL_DB_PORT}/security?allowPublicKeyRetrieval=true&useSSL=false


    #
    ## Username and password
     username: ${MYSQL_DB_USER}
     password: ${MYSQL_DB_PASSWORD}
server:
  port: 8098