server:
    port: 8050
spring:
  cloud:
    stream:
      kafka:
        binder:

#          brokers: 192.168.99.100:19092
           brokers:  http://${KAFKA_HOST}:${KAFKA_PORT}
      bindings:
        events-out:
          destination: adsToBeConsumed
          contentType: application/json

  zipkin:
#    base-url: http://192.168.99.100:9411/
     base-url: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}




  data:
    elasticsearch:
      repositories:
        enabled: true

#    cluster-nodes: 192.168.99.100:9200

    cluster-nodes: http://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
    cluster-name: ${CLUSTER_NAME:docker-cluster}

  elasticsearch:
    rest:
#      uris: 192.168.99.100:9200
      uris: ${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
lbMarketing:
  app:
    jwtSecret: {$SECRET:jwtlbMarketingSecretKey}
    jwtExpiration: {$EXPIRATION:86400}
security:
    basic:
       enable: false
    ignored: /**