server:
    port: 8050
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.99.100:19092
      bindings:
        events-out:
          destination: adsToBeConsumed
          contentType: application/json

#  zipkin:
#    base-url: http://192.168.99.100:9411/




  data:
    elasticsearch:
      repositories:
        enabled: true

    cluster-nodes: 192.168.99.100:9200
    cluster-name: ${CLUSTER_NAME:docker-cluster}

  elasticsearch:
    rest:
      uris: 192.168.99.100:9200
lbMarketing:
  app:
    jwtSecret: {$SECRET:jwtlbMarketingSecretKey}
    jwtExpiration: {$EXPIRATION:86400}
security:
    basic:
       enable: false
    ignored: /**