server:
    port: 8099
spring:
    kafka:
        consumer:
            bootstrap-servers: {$BOOTSTRAP_SERVER:192.168.99.100:19092}
            group-id: ${GROUP_ID:group_id}
            auto-offset-reset: earliest

    cloud:
      stream:
        kafka:
          binder:
            brokers: 192.168.99.100:19092
        bindings:


          user-event-out:
            destination: userPreferences
            contentType: text/plain
          user-event-in:
            destination: userEvent
            contentType: text/plain

    data:
       elasticsearch:
           repositories:
                enabled: true

       cluster-nodes: 192.168.99.100:9200
       cluster-name: ${CLUSTER_NAME:docker-cluster}

    elasticsearch:
      rest:
        uris: 192.168.99.100:9200
lbMarketing:
    app:
        jwtSecret: {$SECRET:jwtlbMarketingSecretKey}
        jwtExpiration: {$EXPIRATION:86400}