server:
  port: 8048
spring:
  data:
     mongodb:
        host: 192.168.99.100
        port: 27017
        database: stage2
        authentication-database: admin
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.99.100:19092
      bindings:
        request-in:
          destination: requestRecommandation
          contentType: text/plain
        event-in:
          destination: adsToBeConsumed
          contentType: application/json
        recommandation_out:
          destination: recommandation
          contentType: text/plain
        user-event-in:
          destination: userPreferences
          contentType: text/plain
#  zipkin:
#    base-url: http://192.168.99.100:9411/
  application:
      name: preference-recommandation-service
logging:
   level: com.assignment.springboot.mongo=DEBUG

#spring.data.mongodb.username=root
#spring.data.mongodb.password=GH15935746
